pipeline {
    agent any

    tools {
        gradle 'gradle-7.6.1'
        jdk 'jdk-17'
    }

    environment {
        // 본인의 DockerHub username로 수정 해주세요.
        DOCKERHUB_USERNAME = 'paranmul'
        // 배포용 Github - Sprint3를 Fork 후 Username 변경 해주세요.
        RELEASE_GITHUB_URL = 'https://github.com/paranmul/kubernetes-anotherclass-sprint3.git'
        // App용 Github - Api-Tester App 소스코드를 Fork 후 Username 변경 해주세요.
        APP_GITHUB_URL = 'https://github.com/paranmul/kubernetes-anotherclass-api-tester.git'

        APP_VERSION = '3.0.0'
        // 실습 넘버링
        CLASS_NUM = '3211'
    }
    
    stages {
        stage('소스파일 체크아웃') {
            steps {
                git branch: "${APP_VERSION}", url: "${APP_GITHUB_URL}"
            }
        }

        stage('소스 빌드') {
            steps {
                // 755권한 필요 (윈도우에서 Git으로 소스 업로드시 권한은 644)
                sh "chmod +x ./gradlew"
                sh "gradle clean build -x test"
            }
        }

        stage('릴리즈파일 체크아웃') {
            steps {
                checkout scmGit(branches: [[name: '*/main']],
                    extensions: [[$class: 'SparseCheckoutPaths',
                    sparseCheckoutPaths: [[path: "/${CLASS_NUM}"]]]],
					userRemoteConfigs: [[url: "${RELEASE_GITHUB_URL}"]])
            }
        }

        stage('컨테이너 빌드') {
            steps {
                // jar 파일 복사
                sh "cp ./build/libs/app-${APP_VERSION}-SNAPSHOT.jar ./${CLASS_NUM}/build/docker/app-${APP_VERSION}-SNAPSHOT.jar"

                // 도커 빌드
                sh "docker build -t ${DOCKERHUB_USERNAME}/api-tester:${APP_VERSION} ./${CLASS_NUM}/build/docker"
            }
        }

		stage('컨테이너 업로드-test') {
		    steps {
		        // 등록된 Credentials ID ('docker_password')를 사용하여 환경 변수에 주입
		        // Username은 DOCKER_USER에, Password는 DOCKER_PASS에 할당됩니다.
		        withCredentials([
		            usernamePassword(
		                credentialsId: 'docker_password', // 등록된 Credential ID로 변경해주세요.
		                usernameVariable: 'DOCKER_USER',
		                passwordVariable: 'DOCKER_PASS'
		            )
		        ]) {
		            script {
		                // Docker Hub로 이미지 업로드
		                
		                // 1. 보안된 환경 변수를 사용하여 docker login 실행
		                sh "docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}"
		                echo "Login successful. Pushing image..."
		                
		                // 2. docker push 실행
		                // 참고: DOCKERHUB_USERNAME이 'paranmul'이라면 $DOCKER_USER를 사용할 수도 있습니다.
		                sh "docker push ${DOCKERHUB_USERNAME}/api-tester:${APP_VERSION}"
		                
		                // 3. (선택적) 보안을 위해 로그아웃
		                // sh "docker logout"
		            }
		        }
		    }
		}

        stage('쿠버네티스 배포') {
            steps {
                // K8S 배포
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/namespace.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/configmap.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/secret.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/service.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/serviceaccount.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/secret-token.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/role.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/rolebinding.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/deployment.yaml"
            }
        }
    }
}
